ERIDB/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('db.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

db/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.conf.urls.static import static
from db import views

urlpatterns = [
    path('test_yadro/', views.test_yadro),
    path('confluence/', views.confluence_server_imitation),
]

db/models.py
from django.db import models
from django.core.files.storage import FileSystemStorage
import os
from django.conf import settings
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.contrib.postgres.fields.jsonb import JSONField


class OverwriteStorage(FileSystemStorage):
    def get_available_name(self, name,max_length=None):
        if self.exists(name):
            os.remove(os.path.join(settings.MEDIA_ROOT, name))
        return name

db/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

import db.models

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime  # for checking renewal date range.


class UserCreateForm(UserCreationForm):
    first_name = forms.CharField(max_length=130, required=True)
    last_name = forms.CharField(max_length=130, required=True)
    class Meta:
        model = User
        fields = ("username", "last_name", "first_name", "password1", "password2", "email")
    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user


class page_form(forms.Form):
    command = forms.CharField(required=False)
    id = forms.CharField(required=False)
    user = forms.CharField(required=False)
    password = forms.CharField(required=False)
    space = forms.CharField(required=False)
    title = forms.CharField(required=False)
    text = forms.CharField(required=False)

db/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
import requests
from requests.auth import HTTPBasicAuth
import json
from db import forms

# POST /rest/api/content
# GET /rest/api/content/{id}
temp_body = ''
def test_yadro(request):
    print('----- test_yadro -----')
    if request.POST:
        form = forms.page_form(request.POST, request.FILES)
        if form.is_valid():
            try:
                command = form.cleaned_data['command']
                id = form.cleaned_data['id']
                user = form.cleaned_data['user']
                password = form.cleaned_data['password']
                space = form.cleaned_data['space']
                title = form.cleaned_data['title']
                body = form.cleaned_data['text']
                print('- command:', command)
                if command == 'create_page':
                    url = 'http://192.168.0.208:8000/confluence/' # /rest/api/content
                    auth = HTTPBasicAuth(user, password)
                    headers = {'Accept': 'application/json',
                               'Content-Type': 'application/json'}
                    data = {
                        'type': 'page',
                        'title': title,
                        'ancestors': [{'id': None}],
                        'space': {'key': space},
                        'body': {
                            'storage': {
                                'value': body,
                                'representation': 'storage',
                            }
                        }
                    }
                    try:
                        response = requests.post(url,
                                                 auth=auth,
                                                 headers=headers,
                                                 data=data
                                                 ).json()
                    except Exception as err:
                        print("- create_page requests.post exception:", err)
                    # print('id', response['id'])
                    if response['id'] != '':
                        return HttpResponse(response['id'])
                    else:
                        return HttpResponse(False)
                if command == 'get_page' and id:
                    # print('Запрос', user, password, id)
                    url = 'http://192.168.0.208:8000/confluence/'  # /rest/api/content/{id}
                    auth = HTTPBasicAuth(user, password)
                    headers = {'Accept': 'application/json',
                               'Content-Type': 'application/json'}
                    params = dict(id=id, expand=None, status=None, version=None)
                    try:
                        response = requests.get(url,
                                                auth=auth,
                                                headers=headers,
                                                params=params
                                                ).json()
                    except Exception as err:
                        print("- get_page requests.get exception:", err)
                    print('keys:', list(response.keys()))
                    space = response['space']['key']
                    title = response['title']
                    body = response['body']['storage']['value']
                    # print(text)
                    return HttpResponse(json.dumps(dict(space=space, title=title, body=body)))
            except Exception as err:
                print("- test_yadro exception:", err)
                return HttpResponse(False)
    else:
        return render(request, 'db/test_yadro.html')

@csrf_exempt
def confluence_server_imitation(request):
    print('----- confluence_server_imitation -----', request.method)
    if request.method == "POST":
        return HttpResponse(json.dumps({'id': '45'}, ensure_ascii=False))
    if request.method == "GET":
        print('- request:', request.GET)
        page_data = {
            'id': request.GET['id'],
            'type': 'page',
            'title': 'title',
            'ancestors': [{'id': None}],
            'space': {'key': 'space'},
            'body': {
                'storage': {
                    'value': '<p>' + 'Текст страницы ' + str(request.GET['id']) + '<p>',
                    'representation': 'storage',
                }
            }
        }
        print('- HttpResponse -')
        return HttpResponse(json.dumps(page_data, ensure_ascii=False))

db/templates/db/test_yadro.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title> {% block title %}{% endblock %}&ndash; БЭРИ </title>
        <link href="{% static "db/style.css" %}" rel="stylesheet">
        <script src="{% static 'db/jquery.min.js' %}"></script>
    </head>

    <body>
        <div id="" class="container">
            <div id="id_area" class="main_area"> <!-- style="background-color: rgb(201, 201, 201);" -->
                <div id="id_head" class="bugs main_head">
                    <div class="bugs main_head_line block-left">
                        <div class="bugs main_head_line_cell width-100 text-center font_head">Новая страница в пространстве</div>
                    </div>
                </div>
        
                <div id="id_content" class="bugs main_content" style="background-color: rgb(185, 255, 190);">
                <form id="id_form" action="/test_yadro/" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="bugs main_content_line block-left">
                        <div class="bugs main_content_line_cell block-left width-20 text-left font_content" style="height: 40px; padding-top: 10px;">
                            Имя пользователя
                        </div>
                        <div class="bugs main_content_line_cell block-left width-80">
                            <input type="text" class="form-control" id="id_user" name="user" value="Ivan">
                        </div>
                    </div>
                    <div class="bugs main_content_line block-left">
                        <div class="bugs main_content_line_cell block-left width-20 text-left font_content" style="height: 40px; padding-top: 10px;">
                            Пароль
                        </div>
                        <div class="bugs main_content_line_cell block-left width-80">
                            <input type="text" class="form-control" id="id_password" name="password" value="123456">
                        </div>
                    </div>
                    <div class="bugs main_content_line block-left">
                        <div class="bugs main_content_line_cell block-left width-20 text-left font_content" style="height: 40px; padding-top: 10px;">
                            Название пространства
                        </div>
                        <div class="bugs main_content_line_cell block-left width-80">
                            <input type="text" class="form-control" id="id_space" name="space" value="work space">
                        </div>
                    </div>
                    <div class="bugs main_content_line block-left">
                        <div class="bugs main_content_line_cell block-left width-20 text-left font_content" style="height: 40px; padding-top: 10px;">
                            Заголовок документа
                        </div>
                        <div class="bugs main_content_line_cell block-left width-80">
                            <input type="text" class="form-control" id="id_title" name="title" value="work task 1">
                        </div>
                        </div>
                    </div>
                    <div class="bugs main_content_line block-left">
                        <div class="bugs main_content_line_cell block-left width-20 text-left font_content" style="height: 40px; padding-top: 10px;">
                            Тело документа
                        </div>
                        <div class="bugs main_content_line_cell block-left width-100">
                            <textarea id="id_text" style="width: 100%; height: 200px; overflow: scroll;" name="text"><p>тут текст</p></textarea>
                        </div>
                        <div id="id_body" class="bugs main_content_line_cell block-left width-100">
                        </div>
                    </div>
                    <input hidden type="text" class="form-control" id="id_command" name="command" value="">
                    <input hidden type="text" class="form-control" id="id_id" name="id" value="">
                </form>
        
                    <div class="bugs main_content_line block-left">
                        <div class="bugs main_content_line_cell block-left width-100">
                            <button onclick="create_page()" class="btn btn-primary" style="float:left ; width: 50%; height: 40px; margin: 0% 25%;" >
                                Создать
                            </button>
                        </div>
                    </div>

                    <div class="bugs main_content_line block-left">
                        <div class="bugs main_content_line_cell block-left width-100">
                            <button onclick="get_page()" class="btn btn-primary" style="float:left ; width: 50%; height: 40px; margin: 0% 25%;" >
                                Загрузить
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript">
     
            function create_page(){
                console.log('----- create_page -----')
                let error = []
                if ($('#id_user').val().length < 1){
                    error.push("Имя слишком короткое") }
                if ($('#id_password').val().length < 1){
                    error.push("Пароль слишком короткий") }
                if ($('#id_space').val().length < 1){
                    error.push("Название пространства слишком короткое") }
                if ($('#id_title').val().length < 1){
                    error.push("Заголовок документа слишком короткий") }
                if ($('#id_text').val().length < 1){
                    error.push("Текст документа слишком короткий") }
                if ( error.length > 0 ) {
                    alert(error)
                } else {
                    manager_submit_Form('create_page')
                }
            }

            function get_page(){
                console.log('----- get_page -----')
                let error = []
                if ($('#id_user').val().length < 1){
                    error.push("Имя слишком короткое") }
                if ($('#id_password').val().length < 1){
                    error.push("Пароль слишком короткий") }
                if ($('#id_space').val().length < 1){
                    error.push("Название пространства слишком короткое") }
                // if ($('#id_title').val().length < 1){
                //     error.push("Заголовок документа слишком короткий") }
                // if ($('#id_text').val().length < 1){
                //     error.push("Текст документа слишком короткий") }
                if ( error.length > 0 ) {
                    alert(error)
                } else {
                    let page_id = prompt('id страницы', '')
                    manager_submit_Form('get_page', page_id)
                }
            }

            function build_page(){
                console.log('----- build_page -----', page_data)
                if (page_data != undefined && page_data != {}) {
                    // $('#id_user').val(page_data['user'])
                    // $('#id_password').val(page_data['password'])
                    $('#id_space').val(page_data['space'])
                    $('#id_title').val(page_data['title'])
                    $('#id_text').hide()
                    $('#id_body').empty()
                    $('#id_body').append(page_data['body'])
                }
            }

            /* Обмен с сервером */
            let page_data
            function submit_Form(event){
                console.log('----- submit_Form -----')
                event.preventDefault();
                let data = new FormData($(this).get(0)) // console.log("boardRevision:", data.get("boardRevision"))
                $.ajax({
                    url: $(this).attr('action'),
                    type: $(this).attr('method'),
                    data: data,
                    cache: false, 
                    processData: false,
                    contentType: false,
                    success: function (obj_answer_data) {
                        console.log('- answer:', obj_answer_data)
                        if (obj_answer_data != false) {
                            if (obj_answer_data != null){
                                if ($('#id_command').val() == "create_page"){
                                    alert('id: ' + obj_answer_data)
                                } else if ($('#id_command').val() == "get_page"){
                                    page_data = JSON.parse(obj_answer_data)
                                    build_page()
                                }
                            }
                        }
                    },
                    error: function(){
                        console.log('- answer false')
                    }
                })
            }
            $('#id_form').submit(submit_Form)
            function manager_submit_Form(command, data=""){
                console.log("-----  manager_submit_Form -----", command, data)
                if (command == "create_page"){
                    $('#id_command').val( command )
                    $('#id_form').submit()
                }
                if (command == "get_page"){
                    $('#id_command').val( command )
                    $('#id_id').val(data)
                    $('#id_form').submit()
                }
            }
        </script>
    </body>
</html>